media-sync status now allowed for any user

diff --git a/bin/media-sync b/bin/media-sync
--- a/bin/media-sync
+++ b/bin/media-sync
@@ -1,7 +1,7 @@
 #!/bin/bash
 # -*- mode:sh; sh-indentation:2 -*- vim:set ft=sh et sw=2 ts=2:
 #
-# media-sync v1.0 Media Sync
+# media-sync v1.1 Media Sync
 #
 # Author: Scott Shambarger <devel@shambarger.net>
 # Copyright (C) 2020 Scott Shambarger
@@ -41,7 +41,7 @@
 #   TIMEOUT - rsync timeout in secs (default: 300)
 #
 # Required commands (config override in parens):
-#   rsync (RSYNC), pkill (PKILL)
+#   rsync (RSYNC), pkill (PKILL), pgrep (PGREP)
 #
 # Required commands in run as root:
 #   su, realpath
@@ -65,8 +65,6 @@ if [ $EUID -eq 0 ]; then
     exec su -s /bin/bash -c "$(printf "%q " "$rpath" "$@")" $LOCAL_USER
   fi
 fi
-
-[ "$USER" != "$LOCAL_USER" ] && echo "Run as user $LOCAL_USER or root" && exit 1
 
 CONFIG="/etc/media-sync.conf"
 # (new) local user config overrides global
@@ -93,6 +91,7 @@ SEND_SPEED=250
 TIMEOUT=300
 
 PKILL=$(command -v pkill)
+PGREP=$(command -v pgrep)
 RSYNC=$(command -v rsync)
 
 # local all overrides
@@ -179,11 +178,21 @@ for f in "$@"; do
 done
 
 [ ! -x "$PKILL" ] && log "Unable to find pkill (set PKILL config)" && exit 2
+[ ! -x "$PGREP" ] && log "Unable to find pgrep (set PGREP config)" && exit 2
 [ ! -x "$RSYNC" ] && log "Unable to find rsync (set RSYNC config)" && exit 2
 
+if [ "$USER" != "$LOCAL_USER" ]; then
+  [ -n "$cancel" -a -n "$test" ] || {
+    echo "Run as user $LOCAL_USER or root" && exit 1
+  }
+fi
+
 if [ -n "$cancel" ]; then
-  [ -n "$test" ] && signal=0 || signal=USR1
-  "$PKILL" -$signal -u $LOCAL_USER rsync
+  if [ -n "$test" ]; then
+    "$PGREP" -u $LOCAL_USER rsync >/dev/null
+  else
+    "$PKILL" -USR1 -u $LOCAL_USER rsync
+  fi
   rc=$?
   [ $rc -eq 0 ] && status= || status="not "
   [ -n "$test" ] && echo "media-sync is ${status}running" && exit $rc
