dhcpd-watch v1.1 - added rtadvd.conf check, logging fixes

diff --git a/macos/startup/dhcpd-watch b/macos/startup/dhcpd-watch
--- a/macos/startup/dhcpd-watch
+++ b/macos/startup/dhcpd-watch
@@ -1,7 +1,7 @@
 #!/bin/bash
 # -*- mode: shell-script; fill-column: 78 -*-
 #
-# dhcpd-watch v1.0 Spawn dhcpd on VirtualBox network (MacOS host)
+# dhcpd-watch v1.1 Spawn dhcpd on VirtualBox network (MacOS host)
 #
 # Author: Scott Shambarger <devel@shambarger.net>
 # Copyright (C) 2020-22 Scott Shambarger
@@ -40,7 +40,9 @@ LOGFILE="/usr/local/var/log/dhcpd.log"
 
 # rtadvd
 RTADVD="/usr/sbin/rtadvd"
+RTADVD_CONF="/etc/rtadvd.conf"
 RTADVD_PID="/var/run/rtadvd.pid"
+RTADVD_LOG="/usr/local/var/log/rtadvd.log"
 
 # dhcpd6 config (optional)
 DHCP6CFG="/usr/local/etc/dhcpd6.conf"
@@ -174,13 +176,19 @@ disable_ip6_forwarding() {
   sysctl -w net.inet6.ip6.forwarding=0
 }
 
+check_rtadv_conf() {
+  [[ -f $RTADVD_CONF ]] && grep "^${NET}:" "$RTADVD_CONF" && return 0
+  msg "Adding missing $NET to $RTADVD_CONF"
+  echo "${NET}:raflags=mo:" >> "$RTADVD_CONF"
+}
+
 IN_EXIT=
 trap_exit() {
   # ignore SIGTERM while killing jobs
   trap "" SIGTERM SIGCHLD
   IN_EXIT=1 # bash3 workaround
   kill_proc "$DHCPD6_PID" "$DHCPD" -6
-  kill_proc "$RTADVD_PID" "$RTADVD" "$NET"
+  kill_proc "$RTADVD_PID" "$RTADVD" -d "$NET"
   kill_proc "$DHCPD_PID" "$DHCPD" -4
   # kill all non-daemon child procs
   pkill -P $$
@@ -206,9 +214,9 @@ trap_child() {
   exit 3
 }
 
-[ $EUID -eq 0 ] || fail "Must be run as root"
+[[ $EUID -eq 0 ]] || fail "Must be run as root"
 
-[ -n "$1" ] || {
+[[ $1 ]] || {
   msg "Usage: dhcpd-watch <interface>"
   exit 1
 }
@@ -222,20 +230,22 @@ trap trap_exit EXIT
 trap trap_term SIGTERM SIGINT
 
 # check important config
-[ -x "$VBOXM" ] || fail "$VBOXM missing/noexec"
-[ -x "$DHCPD" ] || fail "$DHCPD missing/noexec"
-[ -n "$LOGFILE" ] || fail "dhcpd logfile not set"
+[[ -x $VBOXM ]] || fail "$VBOXM missing/noexec"
+[[ -x $DHCPD ]] || fail "$DHCPD missing/noexec"
+[[ -n $LOGFILE ]] || fail "dhcpd logfile not set"
 
 #
 # Now lets check the drivers
 #
 
-[ -c /dev/vboxdrv ] || {
+[[ -c /dev/vboxdrv ]] || {
 
   # we need to load the vbox drivers
-  [ -x "$VBOXDEV" ] || fail "$VBOXDEV missing/noexec"
+  [[ -x $VBOXDEV ]] || fail "$VBOXDEV missing/noexec"
 
-  "$VBOXDEV" start || exit 5
+  "$VBOXDEV" >&2 start || exit 5
+
+  [[ -c /dev/vboxdrv ]] || fail "/dev/vboxdrv cannot be created"
 }
 
 #
@@ -243,16 +253,16 @@ trap trap_term SIGTERM SIGINT
 #
 
 get_config() { # <key>
-  [ -f "$VBOXCFG" ] || fail "$VBOXCFG missing"
+  [[ -f $VBOXCFG ]] || fail "$VBOXCFG missing"
   grep "<ExtraDataItem.*name=\"HostOnly/$NET/$1\"" "$VBOXCFG" | \
     sed -E 's/.*value="([^"]*)".*/\1/'
 }
 
 # check config
 IP=$(get_config IPAddress)
-[ -n "$IP" ] || fail "Network $NET not in virtualbox hostonlyifs"
+[[ $IP ]] || fail "Network $NET not in virtualbox hostonlyifs"
 IPMASK=$(get_config IPNetMask)
-[ -n "$IPMASK" ] || fail "Network config $NET missing NetMask"
+[[ $IPMASK ]] || fail "Network config $NET missing NetMask"
 
 # optional
 IP6=$(get_config IPV6Address)
@@ -270,7 +280,7 @@ ifconfig $NET | grep -q "inet $IP" || {
 }
 
 # ip6 addresses
-[ -n "$IP6" -a -n "$IP6MASK" ] && {
+[[ $IP6 && $IP6MASK ]] && {
   ifconfig $NET | grep -q "inet6 $IP6" || {
     # "$VBOXM" hostonlyif ipconfig $NET --ipv6 $IP6 --netmasklengthv6 $IP6MASK >&2 || {
     # stupid VBoxManage is broken for ipv6 host-only
@@ -300,11 +310,13 @@ spawn_daemon "$DHCPD_PID" "$LOGFILE" "$DHCPD" -4 -d "$NET"
 
   add_ip6_routes
 
+  check_rtadv_conf
+
   #
   # start radvtd
   #
 
-  spawn_daemon "$RTADVD_PID" "" "$RTADVD" "$NET"
+  spawn_daemon "$RTADVD_PID" "$RTADVD_LOG" "$RTADVD" -d "$NET"
 
   # rtadvd leaves process group, need to watch by pidfile
   watch_daemon "$RTADVD_PID" "$RTADVD" &
